name: tsforecast
channels:
  - conda-forge
  - defaults 
dependencies:
  - python==3.9
  - pip==23.3.2
  - pip:
      - pandas==2.1.4
      - numpy==1.26.3
      - holidays==0.40
      - prophet==1.1.5
      - scikit-learn==1.3.2
      - matplotlib==3.8.2
      - ipykernel==6.28.0
